### ISSUE TITLE
Common-Sense Annotations

### ISSUE THREAD

**Issue by PhilWicke** [nightingal3/Fig-QA#2]
Hello,
Thank you for sharing your code and data. It was a pleasure to read your arxiv paper! I'm very interested in this study and I'm looking for the commonsense annotations for object knowledge, visual metaphors, common-sense social understanding, and cultural knowledge. Unfortunately, I cannot find the annotations file, which should be in the data directory according to your readme.

**Comment by nightingal3** [comment]
Hi there,
Thanks for reading the paper! Sorry for the missing data, we decided to hide the test set after creating the repository, so I removed the commonsense annotation for the test set. I've uploaded the commonsense annotation for the dev set here though: https://github.com/nightingal3/Fig-QA/blob/master/data/commonsense_annotation/dev.csv
